### ISSUE TITLE
Issue-Some initial styling and layout

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ethereum-fullstack#18]
Automated Review Comments
Issues in frontend/src/App.css:
  - (4, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
Issues in frontend/src/App.js:
  - (1, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
