### ISSUE TITLE
Issue-better semantics

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ethereum-fullstack#26]
Automated Review Comments
Issues in frontend/src/App.js:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
