### ISSUE TITLE
Issue-begin form handling

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ethereum-fullstack#28]
Automated Review Comments
Issues in frontend/src/App.js:
  - (1, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (47, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
