### ISSUE TITLE
Issue-begin form

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ethereum-fullstack#34]
Automated Review Comments
Issues in frontend/src/App.js:
  - (9, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (71, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
