### ISSUE TITLE
Issue-add gas price and block number to footer

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ethereum-fullstack#40]
Automated Review Comments
Issues in frontend/src/App.js:
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
