### ISSUE TITLE
Issue-connect handler

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ethereum-fullstack#42]
Automated Review Comments
Issues in frontend/src/App.js:
  - (1, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (98, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
