### ISSUE TITLE
Issue-add balance after connect, need media queries for small devices

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ethereum-fullstack#44]
Automated Review Comments
Issues in frontend/src/App.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
