### ISSUE TITLE
Issue-smart contract interaction working

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ethereum-fullstack#56]
Automated Review Comments
Issues in README.md:
  - (3, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (24, 'TODO found')
  - (28, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
Issues in frontend/src/App.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (45, 'TODO found')
  - (49, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
