### ISSUE TITLE
Issue-update for testnet deployment

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ethereum-fullstack#58]
Automated Review Comments
Issues in README.md:
  - (1, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (47, 'TODO found')
  - (47, 'Line exceeds 80 characters')
  - (49, 'TODO found')
  - (51, 'TODO found')
Issues in hardhat.config.js:
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
Issues in scripts/deploy.js:
  - (4, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
