### ISSUE TITLE
Issue-fix tests

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ethereum-fullstack#6]
Automated Review Comments
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
Issues in test/simple-storage-test.js:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
