### ISSUE TITLE
Issue-updates for rinkeby deployment

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ethereum-fullstack#62]
Automated Review Comments
Issues in README.md:
  - (1, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (89, 'Line exceeds 80 characters')
  - (91, 'Line exceeds 80 characters')
  - (98, 'Line exceeds 80 characters')
  - (102, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
  - (106, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (111, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (152, 'Line exceeds 80 characters')
  - (159, 'TODO found')
  - (159, 'Line exceeds 80 characters')
  - (160, 'Line exceeds 80 characters')
  - (166, 'TODO found')
  - (169, 'TODO found')
Issues in hardhat.config.js:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')

**Comment by lind0118** [comment]
I got it.
