### ISSUE TITLE
Issue-Begin readme

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ethereum-fullstack#8]
Automated Review Comments
Issues in README.md:
  - (3, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (81, 'TODO found')
  - (91, 'Line exceeds 80 characters')
  - (103, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')
  - (125, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (152, 'Line exceeds 80 characters')
  - (154, 'Line exceeds 80 characters')
  - (157, 'Line exceeds 80 characters')
  - (178, 'Line exceeds 80 characters')
  - (180, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
