### ISSUE TITLE
Issue-document and simplify code

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ethereum-fullstack#84]
Automated Review Comments
Issues in frontend/src/App.js:
  - (1, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (95, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
